version: '3'

volumes:
  postgres:

services:

  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    # env_file:
    #   - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:11.5
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
